name: semforest
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=3.0.0
  - async-lru=2.0.4
  - attrs=25.3.0
  - babel=2.16.0
  - beautifulsoup4=4.12.3
  - blas=2.131
  - blas-devel=3.9.0
  - bleach=6.2.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.4.26
  - certifi=2025.4.26
  - cffi=1.17.1
  - comm=0.2.1
  - debugpy=1.8.11
  - decorator=5.1.1
  - defusedxml=0.7.1
  - exceptiongroup=1.2.2
  - executing=0.8.3
  - gensim=4.3.3
  - h11=0.14.0
  - h2=4.2.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - idna=3.10
  - ipykernel=6.29.5
  - ipython=9.1.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - json5=0.9.25
  - jsonschema=4.23.0
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.12.0
  - jupyter_server=2.15.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.3.4
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - ld_impl_linux-64=2.43
  - libblas=3.9.0
  - libcblas=3.9.0
  - libexpat=2.7.0
  - libffi=3.4.6
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libgomp=14.2.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libopenblas=0.3.29
  - libsodium=1.0.18
  - libsqlite=3.49.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.6
  - mistune=3.1.2
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - notebook-shim=0.2.4
  - numpy-base=1.26.4
  - openblas=0.3.29
  - openssl=3.5.0
  - outcome=1.3.0.post0
  - overrides=7.4.0
  - packaging=24.2
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pexpect=4.8.0
  - pip=25.1
  - platformdirs=4.3.7
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.22
  - pygments=2.19.1
  - pysocks=1.7.1
  - python=3.11.12
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.20.0
  - python-json-logger=3.2.1
  - python_abi=3.11
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - readline=8.2
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - scipy=1.15.2
  - selenium=4.31.0
  - selenium-manager=4.31.0
  - send2trash=1.8.2
  - setuptools=79.0.1
  - smart_open=7.1.0
  - sniffio=1.3.1
  - sortedcontainers=2.4.0
  - soupsieve=2.5
  - sqlite=3.49.1
  - stack_data=0.2.0
  - terminado=0.17.1
  - tinycss2=1.4.0
  - tk=8.6.13
  - tornado=6.4.2
  - traitlets=5.14.3
  - trio=0.30.0
  - trio-websocket=0.12.2
  - typing-extensions=4.13.2
  - typing_extensions=4.13.2
  - urllib3=2.4.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - wrapt=1.17.2
  - wsproto=1.2.0
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - anyio==4.6.2.post1
      - argostranslate==1.9.6
      - charset-normalizer==3.4.0
      - click==8.1.7
      - contourpy==1.3.0
      - countryinfo==0.1.2
      - ctranslate2==4.6.0
      - cycler==0.12.1
      - deep-translator==1.11.4
      - distro==1.9.0
      - fasttext==0.9.3
      - filelock==3.16.1
      - fonttools==4.54.1
      - frozenlist==1.5.0
      - fsspec==2024.10.0
      - fuzzy-c-means==1.7.2
      - httpcore==1.0.7
      - httpx==0.27.2
      - huggingface-hub==0.23.2
      - jinja2==3.0.1
      - jiter==0.7.1
      - joblib==1.4.2
      - jsonschema-specifications==2024.10.1
      - kiwisolver==1.4.7
      - matplotlib==3.6.3
      - mpmath==1.3.0
      - msgpack==1.1.0
      - networkx==3.1
      - nltk==3.9.1
      - numpy==1.23.5
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.1.105
      - openai==1.55.0
      - pandas==2.2.3
      - pillow==11.0.0
      - protobuf==5.28.3
      - pybind11==2.13.6
      - pycountry==23.12.11
      - pydantic==2.10.1
      - pydantic-core==2.27.1
      - pyparsing==3.2.0
      - pytz==2024.2
      - ray==2.10.0
      - referencing==0.35.1
      - regex==2024.9.11
      - rpds-py==0.20.0
      - sacremoses==0.0.53
      - safetensors==0.4.5
      - scikit-learn==1.6.1
      - seaborn==0.11.1
      - sentence-transformers==3.3.1
      - sentencepiece==0.2.0
      - six==1.16.0
      - spicy==0.16.0
      - stanza==1.1.1
      - sympy==1.13.3
      - tabulate==0.8.10
      - threadpoolctl==3.6.0
      - tiktoken==0.8.0
      - tokenizers==0.20.1
      - torch==2.2.2
      - torchvision==0.17.2
      - tqdm==4.67.0
      - transformers==4.46.0
      - triton==2.2.0
      - typer==0.9.4
      - tzdata==2025.1
      - unidecode==1.3.8
      - wikidata==0.8.1
